FROM mongo:latest

EXPOSE 27017

# This DockerFile only displays the possibility of running MongoDB in a container.
# For this project, I will make use of MongoDB Atlas and allow MongoDB to deal with the underlying infrastructure.
